//netherwart (you can find this in nether ) to go to nether you will need 11 obsidian and flintandsteel to ignite the portal
//endflour (can be found in the end  ) you will need eyes of enders you ender pearl and blaze powder both found in the nether
// endereggs(can be found in the end)
//nethersugar (can be found in the nether)
//rottenflesh (can be found in zombfied things)
//hoglinmilk (can be found in the nether)